import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dmSans = localFont({
  src: [
    {
      path: './fonts/DMSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/DMSans-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/DMSans-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/DMSans-Medium.woff',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-dm-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Bento grid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased bg-[#f5f5f5]`}
      >
        {children}
      </body>
    </html>
  );
}
